name: ms_gromacs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10*
  - gromacs=2025.4=nompi*
  - matplotlib
  - nglview=3.1.1
  - mdtraj
  - ipywidgets=7.7.2
  - notebook
  - numpy
  - requests
  - pandas
  - seaborn
  - compilers
  - openmpi
  - cmake
  - pip:
    - plotxvg
